### ISSUE TITLE
Authorization failed in UI

### ISSUE THREAD

**Issue by jeffbrl** [SuperNG6/docker-aria2#96]
Thank you for developing this software and sharing it with the community.

When I launch docker-aria2 using docker compose, I get "Authorization Failed" messages in the UI. I suspect I am making a mistake as I am using Google Translate to read the documentation.

Here is my docker compose file.

```
services:
  aria2:
    image: superng6/aria2:a2b-latest
    container_name: aria2
    cap_add:
      - NET_ADMIN
    networks:
      ipvlan0:
        ipv4_address: 192.168.x.y
    environment:
      - USER_NAME=<redacted>
      - PASSWORD=<redacted>
      - ENABLE_PASSWORD=true
      - PUID=1026
      - PGID=100
      - TZ=Americas/New_York
      - SECRET=<redacted>
      - CACHE=512M
      - PORT=6800
      - WEBUI=true
      - WEBUI_PORT=7002
      - BTPORT=32516
      - UT=true
      - QUIET=true
      - SMD=true
      - A2B=true
      - CRA2B=2h
    volumes:
      - aria2_config:/config
      - aria2_download:/downloads
      - /lib/modules:/lib/modules
    restart: unless-stopped  
    
networks:
  ipvlan0:
    external: true
volumes:
  aria2_config: 
    external: true
  aria2_download:
    external: true
```

Is there an additional configuration required to address authorization?
