### ISSUE TITLE
对于屏蔽迅雷的日志，有开关关闭这些日志输出吗

### ISSUE THREAD

**Issue by yingguqing** [SuperNG6/docker-aria2#99]
[aria2b] 6/7/2025, 1:20:05 PM Blocked: 240e:b8f:9463:2400:1140:d9ed:40:d580 XL 迅雷在线 (Xunlei) 0.0.1.9
[aria2b] 6/7/2025, 1:21:05 PM Blocked: 240e:30c:4f2d:9600:c4cb:d96e:1cb5:fec7 XL 迅雷在线 (Xunlei) 0.0.1.9
[aria2b] 6/7/2025, 1:21:10 PM Blocked: 240e:3a3:20b8:6940:8df0:4f8c:395e:4e21 XL 迅雷在线 (Xunlei) 0.0.1.9
[aria2b] 6/7/2025, 1:22:20 PM Blocked: 2409:8d14:2074:ddc:c182:dbf8:a096:3486 XL 迅雷在线 (Xunlei) 0.0.1.9
[aria2b] 6/7/2025, 1:22:45 PM Blocked: 240e:353:4f22:1300:f962:aa0f:6948:3aef XL 迅雷在线 (Xunlei) 0.0.1.9
这种日志太多了，有开关来关闭这些日志输出吗

**Comment by SuperNG6** [comment]
暂不考虑该功能

**Comment by ysmintor** [comment]
> [aria2b] 6/7/2025, 1:20:05 PM Blocked: 240e:b8f:9463:2400:1140:d9ed:40:d580 XL 迅雷在线 (Xunlei) 0.0.1.9 [aria2b] 6/7/2025, 1:21:05 PM Blocked: 240e:30c:4f2d:9600:c4cb:d96e:1cb5:fec7 XL 迅雷在线 (Xunlei) 0.0.1.9 [aria2b] 6/7/2025, 1:21:10 PM Blocked: 240e:3a3:20b8:6940:8df0:4f8c:395e:4e21 XL 迅雷在线 (Xunlei) 0.0.1.9 [aria2b] 6/7/2025, 1:22:20 PM Blocked: 2409:8d14:2074:ddc:c182:dbf8:a096:3486 XL 迅雷在线 (Xunlei) 0.0.1.9 [aria2b] 6/7/2025, 1:22:45 PM Blocked: 240e:353:4f22:1300:f962:aa0f:6948:3aef XL 迅雷在线 (Xunlei) 0.0.1.9 这种日志太多了，有开关来关闭这些日志输出吗

可以考虑将日志大小限制到多少， docker logging 模块考虑试试

**Comment by SuperNG6** [comment]
如果是觉得日志占用空间可以这样
```
services:

  singbox:
    image: superng6/singbox:v1.12.1
    container_name: singbox
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/config.json:/etc/sing-box/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```
